---
title: Результат работы сервиса
description: Описание и примеры использования результата работы сервиса
prev: Вызов сервиса
next: Информация о сервисе
---

# Результат работы сервиса

Сервис после вызова имеет результата работы, если до этого не было выкинуто исключение.
Результат работы может быть успешный и провальный.

## Успешный результат

Успешный результат — это результат работы сервиса, когда внутри все прошло без каких-либо проблем.

В таком случае этот пример:

```ruby
service_result = UsersService::Accept.call(user: User.first)
```

Будет возвращать это:

```ruby
# => <Servactory::Result @failure?=false, @success?=true, @user=..., @user?=true>
```

## Провальный результат

Провальный результат — это результат работы сервиса, когда внутри произошла ожидаемая проблема.
Под ожидаемой проблемой имеется ввиду что не было получено исключение, а возникшая проблема, например, была вызвана через один из `fail!` методов.

Провальный результат работы сервиса может присутствовать только при вызове через `.call`, метод.
Это необходимо, например, чтобы иметь возможность обработать результат ответа от внешнего API.

Пример результата при возникшей проблеме:

```ruby
# => <Servactory::Result @error=There is some problem with the user, @failure?=true, @success?=false>
```

## Содержимое результата

`Result` независимо от успеха или провала имеет набор данных.

При успешной работе доступны все output атрибуты,
а также доступны методы хелперы `success?` и `failure?`,
которые могут помочь определить сценарий для дальнейшей работы.

```ruby
service_result = UsersService::Accept.call(user: User.first)

service_result.success? # => true
service_result.failure? # => false
```

При неудачной работе сервиса `Result` будет также содержать `error` с полным описанием ошибки.

```ruby
service_result = UsersService::Accept.call(user: User.first)

service_result.success? # => false
service_result.failure? # => true

service_result.error
# => #<ApplicationService::Errors::Failure: There is some problem with the user>
```

Про неудачную работу сервиса вы можете более подробно узнать [здесь](../exceptions/failure).
